bp_video_dash:
    path:     /dashboard/{tag}/{page}
    defaults: { _controller: BpVideoBundle:Dashboard:index, tag: null, page: 1 }

bp_video_tag_suggestions:
    path:     /ajax/tag-suggestions/{name}
    defaults: { _controller: BpVideoBundle:Ajax:tagSuggetions }
